# Generated by Django 5.2.5 on 2025-08-24 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "clerk_user_id",
                    models.CharField(db_index=True, help_text="Unique user ID from Clerk", max_length=255, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, help_text="User's email address from Clerk", max_length=255, unique=True
                    ),
                ),
                ("first_name", models.CharField(blank=True, help_text="User's first name from Clerk", max_length=255)),
                ("last_name", models.CharField(blank=True, help_text="User's last name from Clerk", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, help_text="Last time user data was synced from Clerk", null=True),
                ),
            ],
            options={
                "db_table": "accounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="site",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The account that owns this site",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sites",
                to="server.account",
            ),
        ),
    ]
