# Generated by Django 5.2.5 on 2025-08-24 22:05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_account_site_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the account",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
