# Generated by Django 5.2.5 on 2025-08-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0003_add_uuid_to_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="owner",
        ),
        migrations.AddField(
            model_name="site",
            name="user_id",
            field=models.CharField(
                db_index=True, default="temp_user", help_text="User ID of the site owner (from Clerk)", max_length=255
            ),
        ),
        migrations.DeleteModel(
            name="Account",
        ),
    ]
