# Generated by Django 4.2.23 on 2025-08-28 05:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0004_remove_account_add_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="user_id",
            field=models.CharField(db_index=True, help_text="User ID of the site owner (from Clerk)", max_length=255),
        ),
        migrations.CreateModel(
            name="HourlyPageViewStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the hourly stats record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hour_bucket",
                    models.DateTimeField(
                        db_index=True, help_text="UTC hour bucket (e.g., 2024-01-15 14:00:00+00:00 for 2-3 PM UTC)"
                    ),
                ),
                ("pageview_count", models.IntegerField(default=0, help_text="Total page views in this hour")),
                (
                    "unique_session_count",
                    models.IntegerField(
                        default=0, help_text="Number of unique sessions that had page views in this hour"
                    ),
                ),
                (
                    "last_processed_pageview_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of the last pageview that was processed into this aggregation",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        help_text="The site these stats belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hourly_stats",
                        to="server.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-hour_bucket"],
                "indexes": [
                    models.Index(fields=["site", "hour_bucket"], name="server_hour_site_id_332c08_idx"),
                    models.Index(fields=["hour_bucket"], name="server_hour_hour_bu_e2df18_idx"),
                ],
                "unique_together": {("site", "hour_bucket")},
            },
        ),
    ]
