# Generated by Django 5.2.5 on 2025-08-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0005_alter_site_user_id_hourlypageviewstats"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="hourlypageviewstats",
            new_name="server_hour_site_id_e2e8b2_idx",
            old_name="server_hour_site_id_332c08_idx",
        ),
        migrations.RenameIndex(
            model_name="hourlypageviewstats",
            new_name="server_hour_hour_bu_78d792_idx",
            old_name="server_hour_hour_bu_e2df18_idx",
        ),
        migrations.AlterModelTable(
            name="hourlypageviewstats",
            table="server_hourly_pageviews",
        ),
    ]
