# Generated by Django 5.2.5 on 2025-08-29 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "server",
            "0006_rename_server_hour_site_id_332c08_idx_server_hour_site_id_e2e8b2_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyPageViewStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the daily stats record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_bucket",
                    models.DateField(
                        db_index=True,
                        help_text="UTC day bucket (e.g., 2024-01-15 for January 15th, 2024)",
                    ),
                ),
                (
                    "pageview_count",
                    models.IntegerField(
                        default=0, help_text="Total page views in this day"
                    ),
                ),
                (
                    "unique_session_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of unique sessions that had page views in this day",
                    ),
                ),
                (
                    "last_processed_pageview_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of the last pageview that was processed into this aggregation",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        help_text="The site these stats belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="server.site",
                    ),
                ),
            ],
            options={
                "db_table": "server_daily_pageviews",
                "ordering": ["-day_bucket"],
                "indexes": [
                    models.Index(
                        fields=["site", "day_bucket"],
                        name="server_dail_site_id_306028_idx",
                    ),
                    models.Index(
                        fields=["day_bucket"], name="server_dail_day_buc_499be6_idx"
                    ),
                ],
                "unique_together": {("site", "day_bucket")},
            },
        ),
    ]
