# Kamal deployment configuration for Squirrel Stats API
service: squirrel-stats

# Docker image configuration
image: joshuawootonn/squirrel-stats

# Servers configuration
servers:
  web:
    hosts:
      - 5.161.248.77
  workers:
    hosts:
      - 5.161.248.77
    cmd: ./scripts/start_workers.sh
    options:
      health-cmd: "exit 0"
      health-interval: "30s"
      health-timeout: "5s"
      health-retries: 1

volumes:
  - "/var/lib/squirrel-stats/data:/app/data"

proxy:
  ssl: true
  host: api.usesquirrelstats.com
  app_port: 8000

# Registry configuration (Docker Hub)
registry:
  username: joshuawootonn
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  context: .

# Accessories (Redis only - PostgreSQL is hosted externally)
accessories:
  redis:
    image: redis:7-alpine
    host: 5.161.248.77
    port: 6379
    volumes:
      - /var/lib/squirrel-stats/redis:/data
    cmd: redis-server --appendonly yes

# Environment variables
env:
  clear:
    DJANGO_SETTINGS_MODULE: api.settings_prod
    REDIS_URL: redis://5.161.248.77:6379/0
  secret:
    - SECRET_KEY
    - FRONTEND_URL
    - ALLOWED_HOSTS
    - MAILPACE_API_KEY
    - DEFAULT_FROM_EMAIL
    - DATABASE_URL