version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - CLERK_FRONTEND_API=${CLERK_FRONTEND_API:-https://api.clerk.com}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:7777}
    volumes:
      - .:/app
      - /app/__pycache__
      - sqlite_data:/app/data
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  sqlite_data:
