version: "3.8"

# IMPORTANT: Run docker-compose commands from the /api directory (where this file is located)
# The volume mounts (- .:/app) depend on the current working directory being /api
#
# Correct:   cd api && docker-compose up
# Incorrect: docker-compose -f api/docker-compose.yml up
#
# If you see "python: can't open file '/app/manage.py'" errors, you're likely
# running from the wrong directory!

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  postgres:
    image: postgres:16-alpine
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_DB=squirrel_stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d squirrel_stats"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    build: .
    environment:
      - DEBUG=1
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:7777}
      - REDIS_URL=redis://redis:6379/0
      - MAILPACE_API_KEY=${MAILPACE_API_KEY:-}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-noreply@localhost}
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/squirrel_stats
      - AXIOM_API_TOKEN=${AXIOM_API_TOKEN:-}
      - AXIOM_DOMAIN=${AXIOM_DOMAIN:-api.axiom.co}
      - AXIOM_DATASET=${AXIOM_DATASET:-server}
    volumes:
      - .:/app
      - /app/__pycache__

    command: rq worker aggregations --url redis://redis:6379/0
    depends_on:
      - redis
      - postgres

  scheduler:
    build: .
    environment:
      - DEBUG=1
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:7777}
      - REDIS_URL=redis://redis:6379/0
      - MAILPACE_API_KEY=${MAILPACE_API_KEY:-}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-noreply@localhost}
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/squirrel_stats
      - AXIOM_API_TOKEN=${AXIOM_API_TOKEN:-}
      - AXIOM_DOMAIN=${AXIOM_DOMAIN:-api.axiom.co}
      - AXIOM_DATASET=${AXIOM_DATASET:-server}
    volumes:
      - .:/app
      - /app/__pycache__

    command: >
      sh -c "
        while true; do
          python manage.py queue_current_hour
          sleep 60
        done
      "
    depends_on:
      - redis
      - postgres

  workers:
    build: .
    environment:
      - DEBUG=1
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:7777}
      - REDIS_URL=redis://redis:6379/0
      - MAILPACE_API_KEY=${MAILPACE_API_KEY:-}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-noreply@localhost}
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/squirrel_stats
      - AXIOM_API_TOKEN=${AXIOM_API_TOKEN:-}
      - AXIOM_DOMAIN=${AXIOM_DOMAIN:-api.axiom.co}
      - AXIOM_SERVER_DATASET=${AXIOM_SERVER_DATASET:-server}
      - AXIOM_QUEUE_DATASET=${AXIOM_QUEUE_DATASET:-queue-workers}
    volumes:
      - .:/app
      - /app/__pycache__

    command: ./scripts/start_workers.sh
    depends_on:
      - redis
      - postgres

volumes:
  postgres_data:
  redis_data:
